# Generated by Django 6.0.7 on 2026-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=150)),
                ('muallif', models.CharField(max_length=150)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sahidfalar_soni', models.IntegerField()),
            ],
        ),
    ]
